apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: JobApplication
  annotations:
    github.com/project-slug: Mokshithsaigit/JobApplication
spec:
  type: other
  owner: group:default/guests
  lifecycle: unknown
